# NUMPY

In [7]:
import numpy as np

In [8]:
# From a Python list
a = np.array([1, 2, 3, 4, 5])
print(a)

# Using arange (like range())
b = np.arange(0, 10, 3)
# => [0, 2, 4, 6, 8]
print(b)

# Evenly spaced values
c = np.linspace(0, 1, 4)
# => [0. , 0.25, 0.5, 0.75, 1.]
print(c)

[1 2 3 4 5]
[0 3 6 9]
[0.         0.33333333 0.66666667 1.        ]


## Built-in Functions

In [ ]:
# Zeros and Ones
zeros = np.zeros((2, 2))
print(zeros)
# [[0 0], [0, 0]]
ones  = np.ones((2, 3))
print(ones)

# Fill with a constant
full  = np.full((10, 5), 7)
print(full)

# Random arrays
rand  = np.random.rand(3, 3)
ints  = np.random.randint(0, 10, size=(3, 3))
print(rand)
print(ints)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.45467439 0.12231683 0.20246231]
 [0.42128828 0.45800858 0.53952117]
 [0.64783462 0.50698888 0.09859786]]
[[2 2 7]
 [2 6 1]
 [1 4 1]]


## Array Attributes

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim, a.shape, a.size, a.dtype)   # => 2  (2, 3)  6  int64

2 (2, 3) 6 int64


## Indexing & Slicing

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])

# Access single element
print(a[2])       # => 3

# Modify element
a[3] = 13
print(a)  # => [1, 2, 3, 13, 5, 6]

# 2D indexing
b = np.array([[1,2,3],[4,5,6]])
print(b[1, 2])    # => 6
print(b[0])       # => [1, 2, 3]

3
[ 1  2  3 13  5  6]
6
[1 2 3]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

# Slice with start:stop
a[3:]       # => [4, 5, 6]
a[:2]       # => [1, 2]
a[1:4]      # => [2, 3, 4]

# Step slicing
a[::2]      # => [1, 3, 5]

# 2D slicing
b = np.array([[1,2,3],[4,5,6]])
b[:, 1:]    # => [[2,3],[5,6]]
b[0, :2]    # => [1, 2]

## Element-wise Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Arithmetic between arrays
a + b        # => [5, 7, 9]
a * b        # => [4, 10, 18]
a - b        # => [-3, -3, -3]
a / b        # => [0.25, 0.4, 0.5]

# Scalar operations
a + 10       # => [11, 12, 13]
a * 3        # => [3, 6, 9]
a ** 2       # => [1, 4, 9]

# Comparison operators
a > 2        # => [False, False, True]
a == 2       # => [False, True, False]

In [ ]:
b = np.array([
    [1, 2, 3], 
    [4, 5, 6]])

print(b.ndim, b.shape)
b[0, 0]

2 (2, 3)


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
#print(b[:, :])  # arr[row(0, 2), col(0, 3)]
print(b[:, :2])

"""
b[:] > [[1, 2, 3], [4, 5, 6]]
b[:1] > [[1], [4]]
"""

[[1 2]
 [4 5]]


'\nb[:] > [[1, 2, 3], [4, 5, 6]]\nb[:2] > [[1, 2], [4, 5]]\n'